import SmallCard from "@/components/SmallCard/SmallCard";
import Head from "next/head";
import styled from "styled-components";
import data from "../data.json";

const Heading = styled.h2``;

const Main = styled.main`
  background: white;
  height: 100vh;
`;

export default function Home() {
  console.log("data", data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Main>
        <Heading>Time tracking Dashboard</Heading>
        {data.map((item) => (
          <SmallCard
            key={item.title}
            title={item.title}
            current={item.timeframes.weekly.current}
            previous={item.timeframes.weekly.previous}
            backgroundColor={item.backgroundColor}
          />
        ))}
      </Main>
    </>
  );
}
