import SmallCard from "@/components/SmallCard";
import Head from "next/head";
import styled from "styled-components";

const Heading = styled.h2``;

const Main = styled.main`
  background: white;
  height: 100vh;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Main>
        <div>
          <Heading>Time tracking Dashboard</Heading>
          <SmallCard />
        </div>
      </Main>
    </>
  );
}
